name: Lint and test PRs

on:
  workflow_dispatch:
# Uncomment lines below to enable lint, format and tests on each PR 
#   pull_request:
#     branches:
#       - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # 'dev', 'alpha', default to: 'stable'
          # flutter-version: '1.12.x' # you can also specify exact version of flutter
      
      - run: flutter pub get
      - run: make generate-code
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
