name: Lint and test PRs

on:
  workflow_dispatch:
# Uncomment lines below to enable lint, format and tests on each PR 
#   pull_request:
#     branches:
#       - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
      - uses: monterail/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: make generate-code
      - run: flutter format --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test
